### ISSUE TITLE
Typo in is-dismissable slot prop

### ISSUE THREAD

**Issue by slothtopus** [evo-mark/vue3-snackbar#10]
Hello,

There is a small typo in the `isDismissable` prop. Currently you have to use `isDimissible` to get it to work.

https://github.com/evo-mark/vue3-snackbar/blob/2cd9c40c2f3d7338e862006190cdf234c5f55ca9/src/Vue3SnackbarMessage.vue#L50C64-L50C77

**Comment by craigrileyuk** [comment]
That's how you spell it.

https://www.oed.com/dictionary/dismissible_adj

**Comment by slothtopus** [comment]
Yep, but it's spelled is-dimissible in the slot props:

```
:is-dimissible="props.message.dismissible"
```

**Comment by craigrileyuk** [comment]
Ah, I'm with you. I thought you were talking about 'able' vs 'ible'.

**Comment by craigrileyuk** [comment]
Fixed with version 2.2.2
