### ISSUE TITLE
Where is option to change text color for the snackbar?

### ISSUE THREAD

**Issue by sarwangds** [evo-mark/vue3-snackbar#6]
I am looking into the docs to change text color for the snackbar, but I can't seem to find the option,

also where can I find the instructions to run the project locally for testing and see If I could implement that?
Thanks

**Comment by aktdaaaa** [comment]
> also where can I find the instructions to run the project locally for testing and see If I could implement that?

You can run the demo page locally by executing the following command
`npm run demo`

**Comment by jeremy-wischusen-colpal** [comment]
"And how does one change the font color?"

I was able to do this by setting the messageClass property and applying styles to that class.

**Comment by craigrileyuk** [comment]
Closed with c7816d3
