### ISSUE TITLE
Github Pages demo return 404

### ISSUE THREAD

**Issue by mrleblanc101** [evo-mark/vue3-snackbar#8]
The [demo link](https://south-coast-web.github.io/vue3-snackbar/) at the bottom of [this page](https://southcoastweb.co.uk/open-source-software/vue3-snackbar/) return a 404:
![Screenshot 2023-10-01 at 11 00 03 PM](https://github.com/evo-mark/vue3-snackbar/assets/17392251/5be1dbbb-ed7b-476f-9c91-96cf470b71da)
![271873981-f6204634-4221-4354-8da8-830d278c0624](https://github.com/evo-mark/vue3-snackbar/assets/17392251/f22d0775-f32c-4ef5-8ada-83271537c032)

**Comment by craigrileyuk** [comment]
Thanks for the heads up.

Link is now fixed.
